export const ERROR_CODES = {
  INVALID_CONTENT_TYPE: 'INVALID_CONTENT_TYPE',
  MISSING_REQUIRED_HEADER: 'MISSING_REQUIRED_HEADER',
  INVALID_PROVIDER: 'INVALID_PROVIDER',
  INVALID_CUSTOM_HOST: 'INVALID_CUSTOM_HOST',
  INVALID_CONFIG: 'INVALID_CONFIG',
  UNSUPPORTED_CONFIG_VERSION: 'UNSUPPORTED_CONFIG_VERSION',
  MISSING_PROVIDER_IN_CONFIG: 'MISSING_PROVIDER_IN_CONFIG',
  PROVIDER_AUTHENTICATION_ERROR: 'PROVIDER_AUTHENTICATION_ERROR',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_RATE_LIMIT: 'PROVIDER_RATE_LIMIT',
  PROVIDER_TIMEOUT: 'PROVIDER_TIMEOUT',
  PROVIDER_INTERNAL_ERROR: 'PROVIDER_INTERNAL_ERROR',
  PROVIDER_BAD_REQUEST: 'PROVIDER_BAD_REQUEST',
  NO_HEALTHY_TARGETS: 'NO_HEALTHY_TARGETS',
  GATEWAY_TIMEOUT: 'GATEWAY_TIMEOUT',
  GATEWAY_INTERNAL_ERROR: 'GATEWAY_INTERNAL_ERROR',
  INVALID_API_KEY: 'INVALID_API_KEY',
  INVALID_PROMPT_ID: 'INVALID_PROMPT_ID',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_CONTENT_TYPE]: 'Invalid content type passed',
  [ERROR_CODES.MISSING_REQUIRED_HEADER]: (poweredBy: string) =>
    `Either x-${poweredBy}-config or x-${poweredBy}-provider header is required`,
  [ERROR_CODES.INVALID_PROVIDER]: 'Invalid provider passed',
  [ERROR_CODES.INVALID_CUSTOM_HOST]: 'Invalid custom host',
  [ERROR_CODES.INVALID_CONFIG]:
    'Invalid config passed. You need to pass a valid json',
  [ERROR_CODES.UNSUPPORTED_CONFIG_VERSION]:
    'This version of config is not supported in this route. Please migrate to the latest version',
  [ERROR_CODES.MISSING_PROVIDER_IN_CONFIG]: (poweredBy: string) =>
    `Either x-${poweredBy}-provider needs to be passed. Or the x-${poweredBy}-config header should have a valid config with provider details in it.`,
  [ERROR_CODES.PROVIDER_AUTHENTICATION_ERROR]: 'Provider authentication failed',
  [ERROR_CODES.PROVIDER_NOT_FOUND]:
    'The requested resource was not found at the provider',
  [ERROR_CODES.PROVIDER_RATE_LIMIT]: 'Provider rate limit exceeded',
  [ERROR_CODES.PROVIDER_TIMEOUT]: 'Provider request timed out',
  [ERROR_CODES.PROVIDER_INTERNAL_ERROR]: 'Provider internal server error',
  [ERROR_CODES.PROVIDER_BAD_REQUEST]: 'Invalid request to provider',
  [ERROR_CODES.NO_HEALTHY_TARGETS]:
    'No healthy targets found to process the request',
  [ERROR_CODES.GATEWAY_TIMEOUT]: 'Gateway timeout',
  [ERROR_CODES.GATEWAY_INTERNAL_ERROR]: 'Gateway internal server error',
  [ERROR_CODES.INVALID_API_KEY]: 'Invalid API key passed',
  [ERROR_CODES.INVALID_PROMPT_ID]: 'Invalid prompt id passed',
} as const;

export const ERROR_STATUSES = {
  [ERROR_CODES.INVALID_CONTENT_TYPE]: 400,
  [ERROR_CODES.MISSING_REQUIRED_HEADER]: 400,
  [ERROR_CODES.INVALID_PROVIDER]: 400,
  [ERROR_CODES.INVALID_CUSTOM_HOST]: 400,
  [ERROR_CODES.INVALID_CONFIG]: 400,
  [ERROR_CODES.UNSUPPORTED_CONFIG_VERSION]: 400,
  [ERROR_CODES.MISSING_PROVIDER_IN_CONFIG]: 400,
  [ERROR_CODES.PROVIDER_AUTHENTICATION_ERROR]: 401,
  [ERROR_CODES.PROVIDER_NOT_FOUND]: 404,
  [ERROR_CODES.PROVIDER_RATE_LIMIT]: 429,
  [ERROR_CODES.PROVIDER_TIMEOUT]: 408,
  [ERROR_CODES.PROVIDER_INTERNAL_ERROR]: 500,
  [ERROR_CODES.PROVIDER_BAD_REQUEST]: 400,
  [ERROR_CODES.NO_HEALTHY_TARGETS]: 500,
  [ERROR_CODES.GATEWAY_TIMEOUT]: 504,
  [ERROR_CODES.GATEWAY_INTERNAL_ERROR]: 500,
  [ERROR_CODES.INVALID_API_KEY]: 401,
  [ERROR_CODES.INVALID_PROMPT_ID]: 400,
} as const;
