/**
 * Auto-generated type definitions extracted from OCI TypeScript SDK
 * Source: /Users/naren/Code/research/oci-typescript-sdk/lib/generativeaiinference/lib/model/generic-chat-response.ts
 * Generated: 2025-11-21T22:49:57.174Z
 */

export interface OracleErrorResponse {
  message: string;
  code: string | null;
}

export interface OracleChatCompleteResponse {
  modelId: string;
  chatResponse: GenericChatResponse;
  // unused fields:
  modelVersion: string;
}

export interface GenericChatResponse {
  /**
   * The Unix timestamp (in seconds) of when the response text was generated.
   */
  timeCreated: Date;
  /**
   * A list of generated texts. Can be more than one if n is greater than 1.
   */
  choices: Array<ChatChoice>;
  usage?: Usage;
  /**
   * Specifies the processing type used for serving the request.
   */
  serviceTier?: string;

  apiFormat: string;
}

export interface ChatContent {
  type: string;
  text?: string;
}

export interface Message {
  /**
   * Contents of the chat message.
   */
  content?: Array<ChatContent>;

  role: string;
}

export interface SystemMessage extends Message {
  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;

  role: string;
}

export interface ToolCall {
  /**
   * The ID of the tool call.
   */
  id: string;

  type: string;
  arguments: any;
  name: string;
}

export interface UrlCitation {
  /**
   * Start character index in the response where the citation begins. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  startIndex?: number;
  /**
   * End character index in the response where the citation ends. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  endIndex?: number;
  /**
   * Title of the cited source.
   */
  title?: string;
  /**
   * URL of the cited source.
   */
  url?: string;
}

export interface Annotation {
  /**
   * Type of annotation. For web search citations, this is {@code url_citation}.
   */
  type?: string;
  urlCitation?: UrlCitation;
}

export interface AssistantMessage extends Message {
  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;
  /**
   * The refusal message by the assistant.
   */
  refusal?: string;
  /**
   * The tool calls generated by the model, such as function calls.
   */
  toolCalls?: Array<ToolCall>;
  /**
   * List of annotations generated by the model, including inline citations from web search results.
   */
  annotations?: Array<Annotation>;

  role: string;
}

export interface UserMessage extends Message {
  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;

  role: string;
}

export interface ToolMessage extends Message {
  /**
   * Tool call that this message is responding to. The ID is the unique string generated by the
   */
  toolCallId?: string;

  role: string;
}

export interface DeveloperMessage extends Message {
  /**
   * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
   */
  name?: string;

  role: string;
}

export interface Logprobs {
  /**
   * The text offset.
   */
  textOffset?: Array<number>;
  /**
   * The logarithmic probabilites of the output token.
   */
  tokenLogprobs?: Array<number>;
  /**
   * The list of output tokens.
   */
  tokens?: Array<string>;
  /**
   * The logarithmic probabilities of each of the top k tokens.
   */
  topLogprobs?: Array<{ [key: string]: string }>;
}

export interface CompletionTokensDetails {
  /**
   * Audio tokens present in the completion. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  audioTokens?: number;
  /**
   * When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion.
   *  Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  acceptedPredictionTokens?: number;
  /**
   * Tokens generated by the model for reasoning. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  reasoningTokens?: number;
  /**
   * When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  rejectedPredictionTokens?: number;
}

export interface PromptTokensDetails {
  /**
   * Cached tokens present in the prompt. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  cachedTokens?: number;
  /**
   * Audio tokens present in the prompt. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  audioTokens?: number;
}

export interface Usage {
  /**
   * Number of tokens in the generated completion. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  completionTokens?: number;
  /**
   * Number of tokens in the prompt. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  promptTokens?: number;
  /**
   * Total number of tokens used in the request (prompt + completion). Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  totalTokens?: number;
  completionTokensDetails?: CompletionTokensDetails;
  promptTokensDetails?: PromptTokensDetails;
}

export interface SearchEntryPoint {
  /**
   * The rendered content
   */
  renderedContent?: string;
}

export interface GroundingWebChunk {
  /**
   * The web source's uri
   */
  uri?: string;
  /**
   * The title of the web source
   */
  title?: string;
  /**
   * the domain of the web source
   */
  domain?: string;
}

export interface GroundingChunk {
  web?: GroundingWebChunk;
}

export interface GroundingSupportSegment {
  /**
   * The start index Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  startIndex?: number;
  /**
   * The end index Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  endIndex?: number;
  /**
   * the text in the segment
   */
  text?: string;
}

export interface GroundingSupport {
  segment?: GroundingSupportSegment;
  /**
   * The grounding chunk indices
   */
  groundingChunkIndices?: Array<number>;
}

export interface GroundingMetadata {
  /**
   * The queries to be used for Search suggestions.
   */
  webSearchQueries?: Array<string>;
  searchEntryPoint?: SearchEntryPoint;
  /**
   * Array of objects containing the web sources.
   */
  groundingChunks?: Array<GroundingChunk>;
  /**
   * Array of chunks to connect model response text to the sources in groundingChunks.
   */
  groundingSupports?: Array<GroundingSupport>;
}

export interface ChatChoice {
  /**
   * The index of the chat. Note: Numbers greater than Number.MAX_SAFE_INTEGER will result in rounding issues.
   */
  index: number;
  message:
    | SystemMessage
    | AssistantMessage
    | UserMessage
    | ToolMessage
    | DeveloperMessage;
  /**
    * The reason why the model stopped generating tokens.
* <p>
Stops if the model hits a natural stop point or a provided stop sequence. Returns the length if the tokens reach the specified maximum number of tokens.
* 
    */
  finishReason: string;
  logprobs?: Logprobs;
  usage?: Usage;
  groundingMetadata?: GroundingMetadata;
  /**
   * Specifies the processing type used for serving the request.
   */
  serviceTier?: string;
}

export namespace GenericChatResponse {
  export function getJsonObj(
    obj: GenericChatResponse,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj ? obj : (obj as GenericChatResponse)),
      ...{
        choices: obj.choices || undefined,
        usage: obj.usage || undefined,
      },
    };

    return jsonObj;
  }
  export const apiFormat = 'GENERIC';
  export function getDeserializedJsonObj(
    obj: GenericChatResponse,
    isParentJsonObj?: boolean
  ): object {
    const jsonObj = {
      ...(isParentJsonObj ? obj : (obj as GenericChatResponse)),
      ...{
        choices: obj.choices || undefined,
        usage: obj.usage || undefined,
      },
    };

    return jsonObj;
  }
}
