import { ANTHROPIC_STOP_REASON } from '../anthropic/types';
import { FINISH_REASON, PROVIDER_FINISH_REASON } from '../types';
import { BEDROCK_STOP_REASON } from '../bedrock/types';
import { VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON } from '../google-vertex-ai/types';
import { GOOGLE_GENERATE_CONTENT_FINISH_REASON } from '../google/types';

export const finishReasonMap = new Map<PROVIDER_FINISH_REASON, FINISH_REASON>([
  // https://docs.anthropic.com/en/api/messages#response-stop-reason
  [ANTHROPIC_STOP_REASON.stop_sequence, FINISH_REASON.stop],
  [ANTHROPIC_STOP_REASON.end_turn, FINISH_REASON.stop],
  [ANTHROPIC_STOP_REASON.pause_turn, FINISH_REASON.stop],
  [ANTHROPIC_STOP_REASON.tool_use, FINISH_REASON.tool_calls],
  [ANTHROPIC_STOP_REASON.max_tokens, FINISH_REASON.length],
  // https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html#API_runtime_Converse_ResponseSyntax
  [BEDROCK_STOP_REASON.end_turn, FINISH_REASON.stop],
  [BEDROCK_STOP_REASON.tool_use, FINISH_REASON.tool_calls],
  [BEDROCK_STOP_REASON.max_tokens, FINISH_REASON.length],
  [BEDROCK_STOP_REASON.stop_sequence, FINISH_REASON.stop],
  [BEDROCK_STOP_REASON.guardrail_intervened, FINISH_REASON.content_filter],
  [BEDROCK_STOP_REASON.content_filtered, FINISH_REASON.content_filter],
  // https://cloud.google.com/vertex-ai/generative-ai/docs/reference/nodejs/latest/vertexai/finishreason?hl=en
  [VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.STOP, FINISH_REASON.stop],
  [VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.RECITATION, FINISH_REASON.stop],
  [VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.OTHER, FINISH_REASON.stop],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.FINISH_REASON_UNSPECIFIED,
    FINISH_REASON.stop,
  ],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.MAX_TOKENS,
    FINISH_REASON.length,
  ],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.SAFETY,
    FINISH_REASON.content_filter,
  ],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.PROHIBITED_CONTENT,
    FINISH_REASON.content_filter,
  ],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.BLOCKLIST,
    FINISH_REASON.content_filter,
  ],
  [
    VERTEX_GEMINI_GENERATE_CONTENT_FINISH_REASON.SPII,
    FINISH_REASON.content_filter,
  ],
  // https://ai.google.dev/api/generate-content#FinishReason
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.FINISH_REASON_UNSPECIFIED,
    FINISH_REASON.stop,
  ],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.STOP, FINISH_REASON.stop],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.MAX_TOKENS, FINISH_REASON.length],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.SAFETY, FINISH_REASON.content_filter],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.RECITATION, FINISH_REASON.stop],
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.LANGUAGE,
    FINISH_REASON.content_filter,
  ],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.OTHER, FINISH_REASON.stop],
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.BLOCKLIST,
    FINISH_REASON.content_filter,
  ],
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.PROHIBITED_CONTENT,
    FINISH_REASON.content_filter,
  ],
  [GOOGLE_GENERATE_CONTENT_FINISH_REASON.SPII, FINISH_REASON.content_filter],
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.MALFORMED_FUNCTION_CALL,
    FINISH_REASON.stop,
  ],
  [
    GOOGLE_GENERATE_CONTENT_FINISH_REASON.IMAGE_SAFETY,
    FINISH_REASON.content_filter,
  ],
]);
