name: Run Gateway tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  gateway-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Start gateway
        run: npm run dev
      - name: Run gateway tests
        run: npm run test:gateway

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}