name: Run Gateway tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  gateway-tests:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Checkout current branch head
        run: git checkout ${{ github.head_ref }}
      - name: Install dependencies
        run: npm ci
      - name: Run gateway tests
        run: npm run test:gateway

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}