name: Auto Triage Label

on:
  issues:
    types: [opened]

jobs:
  label_issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Add Triage Label
        uses: actions/github-script@v7.0.1
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['triage']
            })
          github-token: ${{secrets.GITHUB_TOKEN}}
